#!/bin/bash

commands=(
    "Change Hash"
    "Compare Directories"
    "Delete Duplicate"
    "Delete Empty Folders"
    "Delete Filename Keyword"
    "Empty Directory Contents"
    "Give Random Name"
    "Mass Uppercase"
    "Rename Detailed Files"
    "Sort by File Format"
    "Sort by Filetype"
    "Sort by Title"
    "Sort by Year"
    "Quit"
)

selected=0

# Function to display the list and highlight the selected item
display_list() {
    clear
    echo -e "\033[1m  Archivist Tools\033[0m\n  ---------------"
    for i in "${!commands[@]}"; do
        if [ $i -eq $selected ]; then
            echo -e "\033[1m➤ ${commands[$i]}\033[0m\n"
        else
            echo -e "  ${commands[$i]}\n"
        fi
    done
}

# Function to execute the selected command
execute_command() {
    case ${commands[$selected]} in
        "Change Hash") 
            python3 Archivist-Tools/tools/change-hash.py
            read -p "Press Enter to return to the menu..."
            ;;
        "Compare Directories")
            python3 Archivist-Tools/tools/compare-directories.py
            read -p "Press Enter to return to the menu..."
            ;;
        "Delete Duplicate") 
            python3 Archivist-Tools/tools/delete-duplicate.py
            read -p "Press Enter to return to the menu..."
            ;;
        "Delete Empty Folders") 
            python3 Archivist-Tools/tools/delete-empty-folders.py
            read -p "Press Enter to return to the menu..."
            ;;
        "Delete Filename Keyword") 
            python3 Archivist-Tools/tools/delete-filename-keyword.py
            read -p "Press Enter to return to the menu..."
            ;;
        "Empty Directory Contents") 
            python3 Archivist-Tools/tools/empty-directory-contents.py
            read -p "Press Enter to return to the menu..."
            ;;
        "Give Random Name") 
            python3 Archivist-Tools/tools/give-random-name.py
            read -p "Press Enter to return to the menu..."
            ;;
        "Mass Uppercase") 
            python3 Archivist-Tools/tools/mass-uppercase.py
            read -p "Press Enter to return to the menu..."
            ;;
        "Rename Detailed Files") 
            python3 Archivist-Tools/tools/rename-detailed-files.py
            read -p "Press Enter to return to the menu..."
            ;;
        "Sort by File Format") 
            python3 Archivist-Tools/tools/sort-by-file-format.py
            read -p "Press Enter to return to the menu..."
            ;;
        "Sort by Filetype") 
            python3 Archivist-Tools/tools/sort-by-filetype.py
            read -p "Press Enter to return to the menu..."
            ;;
        "Sort by Title") 
            python3 Archivist-Tools/tools/sort-by-title.py
            read -p "Press Enter to return to the menu..."
            ;;
        "Sort by Year") 
            python3 Archivist-Tools/tools/sort-by-year.py
            read -p "Press Enter to return to the menu..."
            ;;
        "Quit") 
            echo -e "\n\033[1mExiting script\033[0m"
            exit 0
            ;;
        *) 
            echo -e "\nInvalid selection"
            ;;
    esac
}

# Main loop
while true; do
    display_list

    read -sn 1 key

    case $key in
        "A") ((selected--)); [ $selected -lt 0 ] && selected=$(( ${#commands[@]} - 1 ));;
        "B") ((selected++)); [ $selected -ge ${#commands[@]} ] && selected=0 ;;
        "") execute_command ;;
        *) ;;
    esac
done
